name = "PowerGraphs"
uuid = "4cf3ad31-9d4e-4532-9fdd-b80a3a06e24f"
authors = ["Sigurd Hofsmo Jakobsen <sigurd.jakobsen@sintef.no>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Fontconfig = "186bb1d3-e1f7-5a2c-a377-96d770f13627"
GraphDataFrameBridge = "3c71623a-a715-5176-9801-629b201a4880"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
